FT_DPCM_PTR=$c000
	.export _Bang_music_data
;this file for FamiTone2 library generated by text2data tool

_Bang_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env2,@env4,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env3,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cd,$c8,$c5,$c3,$c1,$00,$04
@env2:
	.byte $cc,$c9,$c6,$c4,$c3,$c3,$c4,$ca,$cd,$00,$08
@env3:
	.byte $cd,$ca,$c9,$c8,$c6,$c5,$c5,$c4,$c4,$c4,$00,$09
@env4:
	.byte $c0,$04,$c0,$00,$02


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $00,$86,$33,$37,$33,$3b,$33,$37,$33,$33,$33,$37,$33,$3b,$33,$37
	.byte $33,$32
@ref1:
	.byte $81,$33,$37,$33,$3b,$33,$37,$33,$33,$33,$37,$33,$3b,$33,$37,$33
	.byte $32
@ref2:
	.byte $00,$33,$37,$33,$3b,$33,$37,$33,$33,$33,$37,$33,$3b,$33,$37,$33
	.byte $32
	.byte $ff,$11
	.word @ref1
	.byte $ff,$11
	.word @ref2
	.byte $ff,$11
	.word @ref1
	.byte $ff,$11
	.word @ref2
	.byte $ff,$11
	.word @ref1
@ref8:
	.byte $36,$95,$36,$85,$3a,$95,$3a,$85
@ref9:
	.byte $40,$95,$40,$85,$3c,$95,$3c,$85
@ref10:
	.byte $3a,$95,$36,$95,$36,$85,$3a,$85
@ref11:
	.byte $8f,$3a,$85,$40,$93,$00,$8f
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref12:
	.byte $86,$14,$83,$00,$14,$83,$00,$14,$83,$00,$14,$83,$00,$14,$83,$00
	.byte $14,$83,$00,$14,$83,$00,$15,$10,$81
@ref13:
	.byte $81,$00,$10,$83,$00,$10,$83,$00,$10,$83,$00,$10,$83,$00,$10,$83
	.byte $00,$10,$83,$00,$10,$83,$00,$10,$81
@ref14:
	.byte $0c,$83,$00,$0c,$83,$00,$0c,$83,$00,$0c,$83,$00,$0c,$83,$00,$0c
	.byte $83,$00,$0c,$83,$00,$0d,$0a,$81
@ref15:
	.byte $81,$00,$0a,$83,$00,$0a,$83,$00,$0a,$83,$00,$0a,$83,$00,$0a,$83
	.byte $00,$0a,$83,$00,$0a,$83,$00,$0a,$81
@ref16:
	.byte $14,$83,$00,$14,$83,$00,$14,$83,$00,$14,$83,$00,$14,$83,$00,$14
	.byte $83,$00,$14,$83,$00,$15,$10,$81
	.byte $ff,$19
	.word @ref13
	.byte $ff,$18
	.word @ref14
	.byte $ff,$19
	.word @ref15
@ref20:
	.byte $1a,$95,$1a,$85,$1e,$95,$1e,$85
@ref21:
	.byte $24,$95,$24,$85,$20,$95,$20,$85
@ref22:
	.byte $1e,$95,$1a,$95,$1a,$85,$1e,$85
@ref23:
	.byte $8f,$1e,$85,$24,$93,$06,$8f
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref24:
	.byte $bf
@ref25:
	.byte $bf
@ref26:
	.byte $bf
@ref27:
	.byte $bf
@ref28:
	.byte $bf
@ref29:
	.byte $bf
@ref30:
	.byte $bf
@ref31:
	.byte $bf
@ref32:
	.byte $bf
@ref33:
	.byte $bf
@ref34:
	.byte $bf
@ref35:
	.byte $bf
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref36:
	.byte $bf
@ref37:
	.byte $bf
@ref38:
	.byte $bf
@ref39:
	.byte $bf
@ref40:
	.byte $bf
@ref41:
	.byte $bf
@ref42:
	.byte $bf
@ref43:
	.byte $bf
@ref44:
	.byte $bf
@ref45:
	.byte $bf
@ref46:
	.byte $bf
@ref47:
	.byte $bf
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref48:
	.byte $bf
@ref49:
	.byte $bf
@ref50:
	.byte $bf
@ref51:
	.byte $bf
@ref52:
	.byte $bf
@ref53:
	.byte $bf
@ref54:
	.byte $bf
@ref55:
	.byte $bf
@ref56:
	.byte $bf
@ref57:
	.byte $bf
@ref58:
	.byte $bf
@ref59:
	.byte $bf
	.byte $fd
	.word @song0ch4loop

